---
  detectors:
    IrresponsibleModule:
      enabled: false
  exclude_paths:
    - _snippetsspec/fixtures/project_info.rb     # one-time test fixture creator
    # - spec/helpers/database_helper.rb   # test helper file not considered
    # - spec/helpers/vcr_helper.rb        # test helper file not considered
    - repostore/ # code files clonsed by CodePraise